### ISSUE TITLE
Check all clients

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#11]
Check.
- [x] Digital Ocean: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525674020
- [x] Gedis Backend: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525675094
- [x] Google Compute: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525675794
- [x] Intercom: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525677895
- [x] itsyouonline: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525678474
- [x] Logger: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525679083
- [x] MongoEngine: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525679611
- [x] Mutlicast: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525679953
- [x] Mysql: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525680889
- [x] Odoo: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525681193
- [x] Postgress: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525681560
- [x] RDP: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525681868
- [x] Sendgrid: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525682181
- [x] SQLAlchemy: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525682500
- [x] SQLite: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525682802
- [x] Tarantool: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525683507
- [x] Telegram bot: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525683735
- [x] TFChain: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525683953
- [x] ZOS: https://github.com/threefoldtech/jumpscaleX_core/issues/11#issuecomment-525684475

**Comment by waleedhammam** [comment]
- Digital Ocean client:

> `j.clients.digitalocean. `
```
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1182, in digitalocean 
    from JumpscaleLibs.clients.digitalocean.DigitalOceanFactory import DigitalOceanFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/digitalocean/DigitalOceanFactory.py", line 2, in <m
odule> 
    from .DigitalOcean import DigitalOcean 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/digitalocean/DigitalOcean.py", line 7, in <module> 
    j.builders.runtimes.python.pip_package_install("python-digitalocean") 
AttributeError: 'group_j__builders__runtimes' object has no attribute 'python' 
```

**Comment by waleedhammam** [comment]
- Gedis Backend client:

> `j.clients.gedis_backend. `

```
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 930, in gedis_backend 
    from Jumpscale.clients.gedis_backends.GedisBackendClientFactory import GedisBackendClientFactory 
  File "/sandbox/lib/jumpscale/Jumpscale/clients/gedis_backends/GedisBackendClientFactory.py", line 2, i
n <module> 
    from .GunClient import GunClient 
  File "/sandbox/lib/jumpscale/Jumpscale/clients/gedis_backends/GunClient.py", line 3, in <module> 
    import websockets 
ModuleNotFoundError: No module named 'websockets' 
```

**Comment by waleedhammam** [comment]
- Google Compute client:

> `j.clients.google_compute. `

```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1002, in google_compute 
    from JumpscaleLibs.clients.google_compute.GoogleComputeFactory import GoogleComputeFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/google_compute/GoogleComputeFactory.py", line 1, in
 <module> 
    from .GoogleCompute import GoogleCompute 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/google_compute/GoogleCompute.py", line 5, in <modul
e> 
    from oauth2client.client import GoogleCredentials 
ModuleNotFoundError: No module named 'oauth2client' 

```

**Comment by waleedhammam** [comment]
- Intercom Client:

> `j.clients.intercom. `

```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1086, in intercom 
    from JumpscaleLibs.clients.intercom.IntercomFactory import Intercom 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/intercom/IntercomFactory.py", line 1, in <module> 
    from .IntercomClient import IntercomClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/intercom/IntercomClient.py", line 1, in <module> 
    from intercom.client import Client 
ModuleNotFoundError: No module named 'intercom' 
```

**Comment by waleedhammam** [comment]
- itsyouonline client:

> `j.clients.itsyouonline. `

```
 File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1026, in itsyouonline 
    from JumpscaleLibs.clients.itsyouonline.IYOFactory import IYOFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/itsyouonline/IYOFactory.py", line 8, in <module> 
    from .IYOClient import IYOClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/itsyouonline/IYOClient.py", line 13, in <module> 
    from clients.itsyouonline.generated.client import Client 
ModuleNotFoundError: No module named 'clients.itsyouonline' 

```

**Comment by waleedhammam** [comment]
- Logger client:

> `j.clients.logger. `
```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1074, in logger 
    from JumpscaleLibs.clients.logger.LoggerFactory import LoggerFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/logger/LoggerFactory.py", line 5, in <module> 
    class LoggerFactory(j.baseclasses.object_config_collection_testtools): 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/logger/LoggerFactory.py", line 8, in LoggerFactory 
    _CHILDCLASS = SSHClientBase 
NameError: name 'SSHClientBase' is not defined 
```

**Comment by waleedhammam** [comment]
- MongoEngine client:

> `j.clients.mongoengine.`

```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1128, in mongoengine 
    from JumpscaleLibs.clients.mongodbclient.MongoEngineFactory import MongoEngineFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/mongodbclient/MongoEngineFactory.py", line 2, in <m
odule> 
    from .MongoEngineClient import MongoEngineClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/mongodbclient/MongoEngineClient.py", line 2, in <mo
dule> 
    from mongoengine import connect 
ModuleNotFoundError: No module named 'mongoengine'
```

**Comment by waleedhammam** [comment]
- Mutlicast client

> `j.clients.multicast. `

```
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 618, in _children_names_get 
    return self._filter(filter=filter, llist=self._children_get(filter=filter)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 235, in _children_get 
    for item in self.find(): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 149, in find 
    for jsxobject in self._findData(**kwargs): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 190, in _findData 
    return self._model.find() 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 68, in __getattr__ 
    raise j.exceptions.NotFound(msg) 
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: EXCEPTION:  
    could not find attribute:_model in multicastfactory (error was:type object 'MulticastFactory' has no
 attribute 
        '_CHILDCLASS') 
```

**Comment by waleedhammam** [comment]
- Mysql Client

> `j.clients.mysql. `
```
Traceback (most recent call last): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1140, in mysql 
    from JumpscaleLibs.clients.mysql.MySQLFactory import MySQLFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/mysql/MySQLFactory.py", line 3, in <module> 
    import mysql.connector 
ModuleNotFoundError: No module named 'mysql' 
```

**Comment by waleedhammam** [comment]
- Odoo Client

> ` j.clients.odoo. `
```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1206, in odoo 
    from JumpscaleLibs.clients.odoo.OdooFactory import OdooFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/odoo/OdooFactory.py", line 2, in <module> 
    from .OdooClient import OdooClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/odoo/OdooClient.py", line 7, in <module> 
    j.builders.runtimes.python.pip_package_install("ERPpeek") 
AttributeError: 'group_j__builders__runtimes' object has no attribute 'python' 
```

**Comment by waleedhammam** [comment]
- Postgress Client

> `j.clients.postgres.  `
```
Traceback (most recent call last): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1104, in postgres 
    from JumpscaleLibs.clients.postgresql.PostgresqlFactory import PostgresqlFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/postgresql/PostgresqlFactory.py", line 2, in <modul
e> 
    import psycopg2 
ModuleNotFoundError: No module named 'psycopg2' 
```

**Comment by waleedhammam** [comment]
- RDP Client

> `j.clients.rdb. `
```
    others = self._children_names_get(filter=filter) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 618, in _children_names_get 
    return self._filter(filter=filter, llist=self._children_get(filter=filter)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 235, in _children_get 
    for item in self.find(): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 149, in find 
    for jsxobject in self._findData(**kwargs): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 190, in _findData 
    return self._model.find() 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 68, in __getattr__ 
    raise j.exceptions.NotFound(msg) 
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: EXCEPTION:  
    could not find attribute:_model in rdbfactory (error was:type object 'RDBFactory' has no attribute '
_CHILDCLASS') 
```

**Comment by waleedhammam** [comment]
- Sendgrid
> `j.clients.sendgrid. `
```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 398, in custom_get_completions 
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1068, in sendgrid 
    from JumpscaleLibs.clients.sendgrid.SendgridFactory import SendgridFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/sendgrid/SendgridFactory.py", line 2, in <module> 
    from .SendGridClient import SendGridClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/sendgrid/SendGridClient.py", line 6, in <module> 
    Attachment = namedtuple("Attachment", ["originalfilename", "binarycontent", "type"]) 
NameError: name 'namedtuple' is not defined 

```

**Comment by waleedhammam** [comment]
- SQLAlchemy

> `j.clients.sqlalchemy. `
```
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1044, in sqlalchemy 
    from JumpscaleLibs.clients.sqlalchemy.SQLAlchemyFactory import SQLAlchemyFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/sqlalchemy/SQLAlchemyFactory.py", line 2, in <modul
e> 
    from .SQLAlchemy import Base, SQLAlchemy 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/sqlalchemy/SQLAlchemy.py", line 3, in <module> 
    from sqlalchemy.orm import sessionmaker 
ModuleNotFoundError: No module named 'sqlalchemy' 
                                                       
```

**Comment by waleedhammam** [comment]
- SQLite

> `j.clients.sqlitedb. `
```
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 618, in _children_names_get 
    return self._filter(filter=filter, llist=self._children_get(filter=filter)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 235, in _children_get 
    for item in self.find(): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 149, in find 
    for jsxobject in self._findData(**kwargs): 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 190, in _findData 
    return self._model.find() 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 68, in __getattr__ 
    raise j.exceptions.NotFound(msg) 
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: EXCEPTION:  
    could not find attribute:_model in dbsqlitefactory (error was:type object 'DBSQLiteFactory' has no a
ttribute 
        '_CHILDCLASS') 
                         
```

**Comment by waleedhammam** [comment]
- Tarantool

> ` j.clients.tarantool. 
`
```
    completions = list(get_completions(self, document, complete_event)) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1062, in tarantool 
    from JumpscaleLibs.clients.tarantool.TarantoolFactory import TarantoolFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/tarantool/TarantoolFactory.py", line 1, in <module>
 
    from .TarantoolClient import TarantoolClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/tarantool/TarantoolClient.py", line 2, in <module> 
    import tarantool 
ModuleNotFoundError: No module named 'tarantool' 
```

**Comment by waleedhammam** [comment]
- Telegram bot

> `j.clients.telegram_bot. 
`
```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1098, in telegram_bot 
    from JumpscaleLibs.clients.telegram_bot.TelegramBotFactory import TelegramBotFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/telegram_bot/TelegramBotFactory.py", line 2, in <mo
dule> 
    from .TelegramBotClient import TelegramBot 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/telegram_bot/TelegramBotClient.py", line 1, in <mod
ule> 
    from telegram.ext import Updater, CommandHandler 
ModuleNotFoundError: No module named 'telegram' 
                                                    
```

**Comment by waleedhammam** [comment]
- TFChain

> `j.clients.tfchain. `
```
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 110, in get_completions 
    obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1176, in tfchain 
    from JumpscaleLibs.clients.tfchain.TFChainClientFactory import TFChainClientFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/tfchain/TFChainClientFactory.py", line 9, in <modul
e> 
    from .TFChainExplorerClient import TFChainExplorerClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/tfchain/TFChainExplorerClient.py", line 6, in <modu
le> 
    from JumpscaleLibs.clients.http.HttpClient import HTTPError 
ModuleNotFoundError: No module named 'JumpscaleLibs.clients.http' 
```

**Comment by waleedhammam** [comment]
- ZOS

> `j.clients.zos. 
`
```
   obj = eval_code(parent, self.get_locals(), self.get_globals()) 
  File "/sandbox/lib/jumpscale/Jumpscale/core/KosmosShell.py", line 41, in eval_code 
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1032, in zos 
    from JumpscaleLibs.clients.zero_os.ZeroOSClientFactory import ZeroOSFactory 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/zero_os/ZeroOSClientFactory.py", line 5, in <module
> 
    from .ZeroOSClient import ZeroOSClient 
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/zero_os/ZeroOSClient.py", line 2, in <module> 
    from JumpscaleLibsExtra.sal_zos.node.Node import Node 
  File "/sandbox/lib/jumpscale/JumpscaleLibsExtra/sal_zos/node/Node.py", line 14, in <module> 
    from ..disks.Disks import Disks, StorageType 
ModuleNotFoundError: No module named 'JumpscaleLibsExtra.sal_zos.disks' 
                                                                        
```

**Comment by waleedhammam** [comment]
working on DigitalOcean client

**Comment by waleedhammam** [comment]
Fixed digitalocean client: https://github.com/threefoldtech/jumpscaleX_libs/commit/46d8f67042f8ae247eb9053598be9bf07c6e2cfb

**Comment by waleedhammam** [comment]
Working on GedisBackend Client

**Comment by waleedhammam** [comment]
Fixed GedisBackend client: https://github.com/threefoldtech/jumpscaleX_core/commit/e3350ba1fa9d93b64a4d62636fb9ec822af37cc6

**Comment by waleedhammam** [comment]
Fixed googlecompute client: https://github.com/threefoldtech/jumpscaleX_libs/commit/339a212ac911a50d3e62aeaebf392a7339cb5f62

**Comment by waleedhammam** [comment]
Fixed Intercom client: https://github.com/threefoldtech/jumpscaleX_libs/commit/6cba28e95984c66074592f27e663ffbc2f8b26b2

**Comment by waleedhammam** [comment]
Fixed IYO client: https://github.com/threefoldtech/jumpscaleX_libs/commit/6f5a5bc709bbdc708b5905fe4cf197e563a372f9

**Comment by waleedhammam** [comment]
Fix Logger Client: https://github.com/threefoldtech/jumpscaleX_libs/commit/e0f43291c2b858073f9f4a99f2c6bc13e355bf0f

**Comment by waleedhammam** [comment]
Fixed MongoEngine Client: https://github.com/threefoldtech/jumpscaleX_libs/commit/4f0a5d234efc34070f14a0592c168ef4dc978bea

**Comment by waleedhammam** [comment]
Fixed Multicast Client https://github.com/threefoldtech/jumpscaleX_core/commit/8ed08a7cf812fbde950c32859e02ab61e15d0866

**Comment by waleedhammam** [comment]
working on zos client

**Comment by waleedhammam** [comment]
fixed zos client: https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/1ac8f808dfbe8d2ab9a1c2a7bb4b9247d7f19240

**Comment by ranatrk** [comment]
working on mysql client

**Comment by waleedhammam** [comment]
Working on Odoo client

**Comment by waleedhammam** [comment]
fixed with https://github.com/threefoldtech/jumpscaleX_core/commit/90568f51073384caad55a93c3990ddd0f46344d9

**Comment by waleedhammam** [comment]
working on Postgress client

**Comment by waleedhammam** [comment]
fixed postgress client: https://github.com/threefoldtech/jumpscaleX_libs/commit/dfa74172f08782fccdfcf2df707a4a439e281ca8

**Comment by waleedhammam** [comment]
working on rdp client

**Comment by waleedhammam** [comment]
Fix rdb client: https://github.com/threefoldtech/jumpscaleX_core/commit/2d738266c625396f378623564c1873f7f0ac0def

**Comment by waleedhammam** [comment]
fix tfchain client: https://github.com/threefoldtech/jumpscaleX_libs/commit/f12d88748b4398c98423c2c3def4e499665a80b7

**Comment by waleedhammam** [comment]
working on telegram client

**Comment by waleedhammam** [comment]
fixed sendgrid client: https://github.com/threefoldtech/jumpscaleX_libs/commit/a8b82ef0a141265f3afec856741d44c903771915

**Comment by ranatrk** [comment]
fixed mysqk client :https://github.com/threefoldtech/jumpscaleX_libs/commit/8babe6d577491dc1606fa06ce6568e53d95c6edb

**Comment by ranatrk** [comment]
working on tarantool client

**Comment by waleedhammam** [comment]
fixed telegram bot: https://github.com/threefoldtech/jumpscaleX_libs/commit/7aa2aae328a1509f24d1e0b8c03f94af6c4acdd7

**Comment by waleedhammam** [comment]
working on sqllite client

**Comment by waleedhammam** [comment]
fixed sqlite client: https://github.com/threefoldtech/jumpscaleX_core/commit/4ed1b9389c29e9fc5be412457dcce9276d50202f

**Comment by waleedhammam** [comment]
working on sqlalchemy client

**Comment by waleedhammam** [comment]
fix sqlalchemy client: https://github.com/threefoldtech/jumpscaleX_libs/commit/86aebedf158e3413417c88843778681e74c34a32

**Comment by ranatrk** [comment]
fixed tarantool client importing: https://github.com/threefoldtech/jumpscaleX_libs/commit/aa20fa0496e659de835bc96b1d6f6b06f3827046

**Comment by Dina-Abd-Elrahman** [comment]
####  `digitalocean` client : 

- test = j.clients.digitalocean.new(name="test") 
-  test.save()
-  j.clients.digitalocean.get(name="test") 
- j.clients.digitalocean.test(reset=True)
- j.clients.digitalocean.count() 
- j.clients.digitalocean.delete("test")
-  j.clients.digitalocean.exists("test")
- j.clients.digitalocean.find()

**Comment by Dina-Abd-Elrahman** [comment]
#### `gedis_backend` client:

- j.clients.digitalocean.get().save()

**Comment by Dina-Abd-Elrahman** [comment]
#### Google_Compute client:

- j.clients.google_compute.new(name="test")
- j.clients.google_compute.count()
- j.clients.google_compute.find()
- j.clients.google_compute.save()
- j.clients.google_compute.get()
- j.clients.google_compute.delete()
- j.clients.google_compute.exists()

**Comment by Dina-Abd-Elrahman** [comment]
#### Intercom client:

-  j.clients.intercom.new(name="test") 
-  j.clients.intercom.find() 
- j.clients.intercom.delete()
-  j.clients.intercom.new(name="test_2")
-  j.clients.intercom.reset()
-  j.clients.intercom.find()
- j.clients.intercom.count()
- j.clients.intercom.exists(name="test")

**Comment by Dina-Abd-Elrahman** [comment]
- verified .
