### ISSUE TITLE
Myjobs cannot start workers in newly installed containers when starting threebot

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#168]
Try:

```
python3 /tmp/jsx container-shell -n depl3bot
```

Then `python3 /tmp/jsx container-shell -n depl3bot`, then start 3bot server using

````
. /sandbox/env.sh; kosmos -p 'j.servers.threebot.install(); j.threebot.package.registration.install(); threefold = j.servers.threebot.default;threefold.web=True;threefold.ssl=True;threefold.start(background=True)'
```

Threebot start error:
```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDB.py", line 273, in redis_server_start
    self.redis_server.start()
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/connectors/redis/RedisServer.py", line 67, in start
    self.gevent_server.serve_forever()
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 367, in serve_forever
    self.start()
  File "/usr/local/lib/python3.6/dist-packages/gevent/baseserver.py", line 305, in start
    self.init_socket()
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 146, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 157, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python3.6/dist-packages/gevent/server.py", line 256, in _tcp_listener
    sock.bind(address)
OSError: [Errno 98] Address already in use: ('0.0.0.0', 6385)
2019-11-07T15:27:57Z <Greenlet at 0x7f2b104ecd48: <bound method BCDB.redis_server_start of bcdb:myjobs
>(port=6385)> failed with OSError
```

**Comment by abom** [comment]
In tmux, workers try to get data from bcdb with workers id of 8, 9...., @xmonader said it might be older data from docker image that causes this kind of issues.

**Comment by xmonader** [comment]
should be fixed along with https://github.com/threefoldtech/jumpscaleX_core/issues/170

**Comment by Pishoy** [comment]
working by new method to start threebot as below 
```
JSX> cl = j.servers.threebot.local_start_default(web=True)                                                                                    
no server running need to start
++ '[' start == kill ']'
++ tmux -f /sandbox/cfg/.tmux.conf has-session -t main
no server running on /tmp/tmux-0/default
++ '[' 1 -eq 1 ']'
++ echo 'no server running need to start'
++ tmux -f /sandbox/cfg/.tmux.conf new -s main -d 'bash --rcfile /sandbox/bin/env_tmux_detach.sh'
++ '[' start '!=' start ']'
JSX>                     
```
- jsx version 
```
3BOTDEVEL:3bot:jumpscaleX_core: git log -1
commit 4409a78552b0915ff671c5217c08e280ffabd0d4 (HEAD -> development, origin/development, origin/HEAD)
Author: xmonader <xmonader@gmail.com>
Date:   Sun Nov 10 14:08:01 2019 +0200

    update bcdbconfigs to ensure the existence of objects regardless of index results

```
