### ISSUE TITLE
ZDB client loses connection with multi threads

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#318]
### Steps
1- Start zdb server test instance
2- Create zdb client 
3- Get bcdb using this client

```python
zdb = j.servers.zdb.test_instance_start()
storclient_admin = zdb.client_admin_get()
storclient = storclient_admin.namespace_new(name="test_zdb", secret="1234")
bcdb = j.data.bcdb.get(name="test_zdb", storclient=storclient)
```
4- Create a bcdb model 
```python
scm = """@url = test.schema.1
text = "" (S)
"""
schema = j.data.schema.get_from_text(scm)
string_model = bcdb.model_get(schema=schema)
```
4- Use this `model` in multi threads to create objects and save them in bcdb.

### Expected Result
Save all object in bcdb.

### Actual Result
Some of object is saved, and the reset is not saved.

### Problem
`redis` loses its connection to zdb server (no idea how is that happens) and create a new one, at this moment it tries to save data into `default` namespace which is read only and got this error
```bash
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/data/bcdb/tests/performance/framework/base.py", line 18, in write_string
    write_time = self.calculate_write_time(string_obj)
  File "/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/data/bcdb/tests/performance/framework/base.py", line 48, in calculate_write_time
    obj.save()
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py", line 215, in save
    o = self._model.set(self)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 370, in set
    obj.id = self.storclient.set(data)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/stor_zdb/clients_impl/sequential.py", line 26, in set
    res = self.redis.execute_command("SET", key1, data)
  File "/root/.local/lib/python3.6/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/root/.local/lib/python3.6/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/root/.local/lib/python3.6/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: Namespace is in read-only mode
```
And by checking zdb server logs, new connection was found, so it has to select the namespace (`test_zdb`) before writing in zdb.

![image](https://user-images.githubusercontent.com/41957921/70434277-76da8f00-1a8c-11ea-9326-fa11dd1cb12f.png)

**Comment by despiegk** [comment]
why do we use threads, that should never be used
and anyhow you cannot use socket over 2 threads
