### ISSUE TITLE
bdcmodel method get_by_name returns a list

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#32]
Since names within one model are supposed to be unique it does not make sense the a method called get_by_name returns a list

**Comment by hossnys** [comment]
verified on branch  development 

```
JSX> schema = """  
   2         @url = jumpscale.test.1 
   3         name* = "" (S) 
   4         test = "" (S)"""                                                                                                                                         

JSX> bcdb = j.data.bcdb.new("samir")                                                                                                                                  
JSX> model = bcdb.model_get(schema=schema)                                                                                                                            
JSX> z = model.new()                                                                                                                                                  
JSX> z.name="test"                                                                                                                                                    
JSX> z.save()                                                                                                                                                         
## .test.1
id: 1
name                : test
test                : 


JSX> model.get_by_name("test")                                                                                                                                        
## .test.1
id: 1
name                : test
test                : 



JSX> model.get_by_name("test55")                                                                                                                                      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 298, in get_by_name
    raise j.exceptions.NotFound("cannot find data with name : %s" % name)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: ?[1;31mEXCEPTION: 
    cannot find data with name : test55?[0;0m

?[1;31mEXCEPTION: 
    cannot find data with name : test55?[0;0m

```
