### ISSUE TITLE
issue with loading the registry package

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#369]
branch: development
```
======================================================================
ERROR: TC560
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/clients/tests/tests_tfgrid_registry.py", line 113, in test001_RegisterationAndPrivacy
    data_id1 = j.clients.tfgrid_registry.register(
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1352, in tfgrid_registry
    self._tfgrid_registry =  TFGridRegistryClient()
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 64, in __init__
    self._init(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/clients/tfgrid_registry/TFGridRegistryClient.py", line 46, in _init
    self.registry_client = self.gedis_client.actors.registry
AttributeError: 'GedisClientActors' object has no attribute 'registry'

----------------------------------------------------------------------
```

**Comment by RafyAmgadBenjamin** [comment]
Fixed on ```development_fixes2``` branch 
* Fixed the registery client in how it loads the package
* Fixed the registery to use long URL instead of short one

**The two commits IDs in two different repos ```jumpscale_core``` and ```jumpscale_threebot```**
d58110d3bc57793a7330e3ba0f353d08ed490f1e
84bb13fabc7deca75a980f4ef91e0d6b7e9f587b

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
