### ISSUE TITLE
SAL.FS: path parsing 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#37]
### Steps:
1- parse `/sandbox` path.
```
j.sal.fs.pathParse("/sandbox")
```
### Actual Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 602, in pathParse
    if j.data.regex.match(regexToFindPriority, dirOrFilename):
  File "/sandbox/lib/jumpscale/Jumpscale/data/regex/RegexTools.py", line 109, in match
    "Cannot do .codetools.regex.match when " "pattern or text parameter is empty"
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.RuntimeError1: ?[1;31mEXCEPTION: 
    Cannot do .codetools.regex.match when pattern or text parameter is empty?[0;0m

?[1;31mEXCEPTION: 
    Cannot do .codetools.regex.match when pattern or text parameter is empty?[0;0m
```
2- parse non-existing path with existCheck=False.
```
j.sal.fs.pathParse("/sandbox/test", existCheck=False)   
```
### Actual Result:
it checks that the path is exists!!
```                                                                                                                                               
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 576, in pathParse
    if self.isDir(path):
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 156, in wrapper
    raise j.exceptions.Value(msg)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.Value1: ?[1;31mEXCEPTION: 
    Argument path in j.sal.fs.isDir expects an existing path value! /sandbox/test does not exist.?[0;0m

?[1;31mEXCEPTION: 
    Argument path in j.sal.fs.isDir expects an existing path value! /sandbox/test does not exist.?[0;0m
```

**Comment by AhmedHanafy725** [comment]
#29

**Comment by zgorizzo69** [comment]
when calling `parsePath` it will call `SystemFSDecorators` that will modify the parameters and especially the path. In this example `j.sal.fs.pathParse("/sandbox/")` "/sandbox/" will be modified to "/sandbox" and then it will be passed to `getDirName` that will call `os.path.dirname` that will return "//" for that path BUT would return "sandbox" if the path would have been "/sandbox/". So to introduce as little change as possible I will take advantage of the `isDir` function inside `parsePath` to make it return the path name when it is a root directory if it is indeed a directory path

**Comment by zgorizzo69** [comment]
when `existCheck=False`  we can't determine if the path is a file or directory path because the decorator will remove the trailing`/` so by default I will treat it as a file path

**Comment by AhmedHanafy725** [comment]
yes this fix the problem, but create another problem.
```
j.sal.fs.pathParse("/sandbox/cfg/jumpscale_config.toml", baseDir="/sandbox/cfg")
```
In this case the `path` is empty string so it can't be indexed.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 626, in pathParse
    if path[len(path) - 1] != "/":
IndexError: string index out of range
```
