### ISSUE TITLE
some myjobs tests fail  and need to check if threebot server will be start by default 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#493]
j.servers.myjobs.test("data_process")                                                                                                                                                                         
```
Thu 30 14:03:40 ts/3_data_process.py -  54 - main                               : EXCEPTION: 
    AssertionError()
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in test
    654    self._test_run(name=name, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _test_run
    53    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in __test_run
    154    self._code_run(name=name, path=path, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _code_run
    75    res = method(self=self, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/tests/3_data_process.py in main
    54    assert job_sch._data._autosave is True
-----------------------------
```
 j.servers.myjobs.test("tmux")                                                                                                                                                                                 
```
['WAITING', 'WAITING']
Thu 30 14:06:01 jobs/tests/8_tmux.py -  42 - main                               : EXCEPTION: 
    AssertionError()
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in test
    654    self._test_run(name=name, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _test_run
    53    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in __test_run
    154    self._code_run(name=name, path=path, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _code_run
    75    res = method(self=self, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/tests/8_tmux.py in main
    42    assert item == "OK"
-----------------------------
```
 j.servers.myjobs.test("dependencies")                                                               
```
Thu 30 14:29:02 ers/myjobs/MyJobs.py -  75 - check_ready                        : EXCEPTION: 
    Job timed out: 93
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in test
    654    self._test_run(name=name, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _test_run
    53    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in __test_run
    154    self._code_run(name=name, path=path, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _code_run
    75    res = method(self=self, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/tests/9_dependencies.py in main
    33    job3.wait()
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobs.py in wait
    114    if self.check_ready(die=die, load=True):
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobs.py in check_ready
    75    raise j.exceptions.Timeout(f"Job timed out: {self.id}")
-----------------------------

```

j.servers.myjobs.test("wait_queues")                                                                
```
Thu 30 14:39:15 obs/MyJobsFactory.py - 603 - results                            : EXCEPTION: 
    TypeError("'NoneType' object is not iterable",)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in test
    654    self._test_run(name=name, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _test_run
    53    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in __test_run
    154    self._code_run(name=name, path=path, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _code_run
    75    res = method(self=self, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/tests/10_wait_queues.py in main
    26    res = self.results(ids=ids, return_queues=["queue_a", "queue_b"])
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in results
    603    for job in self.wait_queues(queue_names=return_queues, size=len(ids), timeout=timeout, die=die)
-----------------------------
```
 j.servers.myjobs.test("workers")                                                                                                                                                                              

```
Thu 30 14:49:15 obs/MyJobsFactory.py - 603 - results                            : EXCEPTION: 
    TypeError("'NoneType' object is not iterable",)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in test
    654    self._test_run(name=name, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _test_run
    53    res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in __test_run
    154    self._code_run(name=name, path=path, obj_key=obj_key, die=die, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/TestTools.py in _code_run
    75    res = method(self=self, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/tests/11_workers.py in main
    31    self.results(ids=[job_sch.id], return_queues=["queue_err"], die=False)
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py in results
    603    for job in self.wait_queues(queue_names=return_queues, size=len(ids), timeout=timeout, die=die)
-----------------------------

'NoneType' object is not iterable
JSX> Process _GProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)                                                                                                                                                                      
  File "/usr/local/lib/python3.6/dist-packages/gipc/gipc.py", line 375, in _child──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    target(*args, **kwargs)          -1005 - systemfs                           : path b'/sandbox/var/codegen/schema_jumpscale_myjobs_job_true.py' does not exist 
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 46, in __init__name for path: /sandbox/var/codegen/schema_jumpscale_myjobs_job_true.py 
    self._init(**kwargs).py          -1311 - systemfs                           : Get directory name of path: /sandbox/var/codegen/schema_jumpscale_myjobs_job_true.py 
  File "/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyWorkerProcess.py", line 79, in _initsandbox/var/codegen/schema_jumpscale_myjobs_job_true.py 
    self.start()SystemFS.py          -1311 - systemfs                           : Get directory name of path: /sandbox/var/codegen/schema_jumpscale_myjobs_job_true.md5 
  File "/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyWorkerProcess.py", line 144, in startandbox/var/codegen/schema_jumpscale_myjobs_job_true.md5 
    self.worker_obj = self.model_worker.get(self.id)s                           : Read file: /sandbox/lib/jumpscale/Jumpscale/data/schema/templates/schema.capnp 
  File "/sandbox/lib/jumpscale/Jumpscale/clients/bcdb/BCDBModelClient.py", line 42, in geths ['/sandbox/var/capnp', 'schema_f305cd22e121592a.capnp'] 
    obj = self.model.get(id)         -1311 - systemfs                           : Get directory name of path: /sandbox/var/capnp/schema_f305cd22e121592a.capnp 
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBDecorator.py", line 63, in wrapper_queue_methodvar/capnp/schema_f305cd22e121592a.capnp 
    res = func(*args, **kwargs)      -2275 - execute                            : execute:whoami 
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 491, in getstop: redis_6380 
    raise j.exceptions.NotFound(f"could not find obj with id:{obj_id} of {self.schema.url}")based on TCP/UDP redis_6380 
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: None      : IS HALTED based on TCP/UDP redis_6380 
JSX>                                                                                                                      
                                                                      
```

**Comment by rkhamis** [comment]
currently not starting myjobs with threebot server
