### ISSUE TITLE
Wikis/Myjobs are broken on development_stabilize

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#60]
When trying to run wikis `kosmos -p 'j.threebot.package.wikis.start()'`, workers started, but every worker raises an error (you can check them by attaching to main tmux session):

```
Traceback (most recent call last):
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 62, in __getattr__
    r = self.__getattribute__(name)
AttributeError: 'MyJobsFactory' object has no attribute 'workers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py", line 251, in _data_loop
    self._data_process_1time(timeout=2)
  File "/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyJobsFactory.py", line 305, in _data_process_1time
    worker_object = self.workers._model.get(objid)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 69, in __getattr__
    raise j.exceptions.NotFound(msg)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: EXCEPTION: 
    could not find attribute:workers in myjobsfactory (error was:'MyJobsFactory' object has no attribute 'workers')
```

**Comment by zgorizzo69** [comment]
I face a different issue while running` kosmos -p 'j.threebot.package.wikis.start()',`
```
    Cloning into 'pgmoon'...
        fatal: unable to connect to github.com:
        github.com[0: 140.82.118.3]: errno=Connection timed out


        Error: Failed installing dependency: https://luarocks.org/pgmoon-1.10.0-1.rockspec - Failed cloning git repository.
```

**Comment by abom** [comment]
@zgorizzo69 That seems to be a network issue.

**Comment by zgorizzo69** [comment]
@abom The problem was that it tried to retrieve packages through git:// protocol, which seems to be blocked on the 3bot container.
git config --global url."https://".insteadOf git:// solved the problem.

**Comment by despiegk** [comment]
the zdb install & sonic install should be part of the threebotserver.install...

**Comment by abom** [comment]
The error in this comment is resolved, we now have a new error (`development_stabilize` branch).

```
--TRACEBACK------------------                                                                 
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyWorkerProcess.py in start                   
    270    res = deadline(job.timeout)(method)(**kwargs)                                      
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyWorkerProcess.py in new_f                   
    17    return f(*args, **kwargs)                                                           
-----------------------------                                                                 
--DATA-----------------------                                                                 
  def load_wiki(name, url):                                                                   
      wiki = j.tools.markdowndocs.load(path=url, name=name)                                   
      wiki.write()                                                                            
-----------------------------                                                                 
                                                                                              
Wed 11 16:01:31 s/MyWorkerProcess.py -  17 - new_f                              : EXCEPTION:  
    cannot execute action                                                                     
    TypeError("load_wiki() missing 2 required positional arguments: 'name' and 'url'",)       
```

> the zdb install & sonic install should be part of the threebotserver.install...

Threebot builder already does that.

**Comment by abom** [comment]
@grimpy Now any method with positional arguments fail, because we pass only kwargs to it.

```
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyWorkerProcess.py in start                   
    270    res = deadline(job.timeout)(method)(**kwargs)                                      
/sandbox/lib/jumpscale/Jumpscale/servers/myjobs/MyWorkerProcess.py in new_f                   
    17    return f(*args, **kwargs)
```

Is this intended?

**Comment by abom** [comment]
Change was added here https://github.com/threefoldtech/jumpscaleX_core/commit/b7177040acc95ef5ea7ec2ec1bfd4ea849ace370#diff-39a80a19b162d5c1498cfd678dd1094dR260.

**Comment by Pishoy** [comment]
verified and wikis started successfully 
` kosmos -p 'j.threebot.package.wikis.start()'`
 - js version 
```
3BOTDEVEL:jsxsecond:jumpscaleX_core: git log -1
commit b118ae46160e2659c14fe74ea254f4c4943f75ad (HEAD -> development, origin/development, origin/HEAD)
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Tue Sep 17 10:21:37 2019 +0200

    Improvements in myjobs gipc loop and logging
    
    Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
```
