### ISSUE TITLE
a badly formed json  request gives an internal server error

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#657]
The request over http contained a malformed json payload, it returned:
```

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost/threefoldfoundation/unlock_service/actors/unlock_service/get_unlockhash_transaction&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>
```
The stacktrace on the server:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "/sandbox/lib/jumpscale/Jumpscale/servers/gedis_http/GedisHTTPFactory.py", line 32, in _enable_cors
    return fn(*args, **kwargs)
  File "/sandbox/lib/jumpscale/threebot_packages/zerobot/webinterface/bottle/gedis.py", line 57, in gedis_http
    data = request.json or {"args": {}}
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 166, in __get__
    if key not in storage: storage[key] = self.getter(obj)
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 1123, in json
    return json_loads(b)
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 93, in <lambda>
    json_loads = lambda s: json_lds(touni(s))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 87 (char 86)
```

**Comment by xmonader** [comment]
fixed in threefoldtech/jumpscaleX_threebot@13ecbdf67a7cc8c3b1700c2ff5775caea05a5757

with malformed json
```
root@3bot:/sandbox# curl -XPOST http://127.0.0.1/zerobot/packagemanager/actors/package_manager/packages_list -H "Content-Type: application/json"  -d '{"args": {"status: "all"}}' 
invalid request body
```
with correct args

```
root@3bot:/sandbox# curl -XPOST http://127.0.0.1/zerobot/packagemanager/actors/package_manager/packages_list -H "Content-Type: application/json"  -d '{"args": {"status": "all"}}' 

{"packages": [{"name": "jumpscale.fruum", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/demo/fruum/", "status": 1, "source": {"name": "fruum", "threebot": "jumpscale", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "demo_fruum", "namespace": "demo", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 14}, {"name": "jumpscale.pastebin", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/demo/pastebin/", "status": 1, "source": {"name": "pastebin", "threebot": "jumpscale", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "demo", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 15}, {"name": "jumpscale.helloworld", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/examples/helloworld/", "status": 1, "source": {"name": "helloworld", "threebot": "jumpscale", "description": "", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "test", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 16}, {"name": "jumpscale.ibiza", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/examples/ibiza/", "status": 1, "source": {"name": "ibiza", "threebot": "jumpscale", "description": "", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "test", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 17}, {"name": "jumpscale.svelte", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/examples/svelte/", "status": 1, "source": {"name": "svelte", "threebot": "jumpscale", "description": "", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "svelte_example", "namespace": "jumpscale", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 18}, {"name": "jumpscale.test_package", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/examples/test_package/", "status": 1, "source": {"name": "test_package", "threebot": "jumpscale", "description": "", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "test", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 19}, {"name": "jumpscale.examples_vuejs", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/examples/vuejs/", "status": 1, "source": {"name": "examples_vuejs", "threebot": "jumpscale", "description": "Example how to make package with vuejs", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "test", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 20}, {"name": "tfgrid.directory", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/directory/", "status": 1, "source": {"name": "directory", "threebot": "tfgrid", "description": "", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "tfgrid_directory", "namespace": "tfgrid_directory", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 21}, {"name": "tfgrid.dns", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/dns/", "status": 1, "source": {"name": "dns", "threebot": "tfgrid", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "tfgrid_dns", "namespace": "tfgrid_dns", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 22}, {"name": "tfgrid.gateway", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/gateway/", "status": 1, "source": {"name": "gateway", "threebot": "tfgrid", "description": "Gateway over tcprouter and coredns", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 23}, {"name": "tfgrid.network", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/network/", "status": 1, "source": {"name": "network", "threebot": "tfgrid", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "tfgrid_network", "namespace": "tfgrid_network", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 24}, {"name": "tfgrid.phonebook", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/phonebook/", "status": 1, "source": {"name": "phonebook", "threebot": "tfgrid", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "phonebook", "namespace": "phonebook", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 25}, {"name": "tfgrid.registration", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/registrationthreebot/", "status": 1, "source": {"name": "registration", "threebot": "tfgrid", "description": "Helper for registration of threebots.", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 26}, {"name": "tfgrid.registry", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/registrygeneric/", "status": 1, "source": {"name": "registry", "threebot": "tfgrid", "description": "Register any type of information", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "registry", "namespace": "registry", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 27}, {"name": "tfgrid.threebot_provisioning", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/threebot_provisioning/", "status": 1, "source": {"name": "threebot_provisioning", "threebot": "tfgrid", "description": "allow anyone to deploy threebots on TFGRID installed on TFGRID explorers", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 28}, {"name": "tfgrid.token", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/token/", "status": 1, "source": {"name": "token", "threebot": "tfgrid", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "tfgrid_tokens", "namespace": "tfgrid_tokens", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 29}, {"name": "tfgrid.workloads", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/workloads/", "status": 1, "source": {"name": "workloads", "threebot": "tfgrid", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "tfgrid_workloads", "namespace": "tfgrid_workloads", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 30}, {"name": "tfgrid_solutions.any_flist", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/any_flist/", "status": 1, "source": {"name": "any_flist", "threebot": "tfgrid_solutions", "description": "create your flist", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 31}, {"name": "tfgrid.gitea", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/gitea/", "status": 1, "source": {"name": "gitea", "threebot": "tfgrid", "description": "Gitea is a painless self-hosted Git service", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 32}, {"name": "tfgrid_solutions.kubernetes_cluster", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/kubernetes_cluster/", "status": 1, "source": {"name": "kubernetes_cluster", "threebot": "tfgrid_solutions", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 33}, {"name": "tfgrid.minecraft", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/minecraft/", "status": 1, "source": {"name": "minecraft", "threebot": "tfgrid", "description": "Minecraft is a sandbox video game", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 34}, {"name": "tfgrid_solutions.minio", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/minio/", "status": 1, "source": {"name": "minio", "threebot": "tfgrid_solutions", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 35}, {"name": "tfgrid.odoo", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/odoo/", "status": 1, "source": {"name": "odoo", "threebot": "tfgrid", "description": "A content management system (CMS) bassed on PHP and MySQL", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 36}, {"name": "tfgrid.taiga", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/taiga/", "status": 1, "source": {"name": "taiga", "threebot": "tfgrid", "description": "Taiga is a free and open-source project management system", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "tfgrid_taiga", "namespace": "tfgrid_taiga", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {"id": "circlesmenu", "value": "Circles", "icon": "mdi mdi-chevron-up-circle-outline", "data": [{"id": "circles", "value": "My Circles", "icon": "mdi mdi-account-supervisor-circle"}, {"id": "circlestories", "value": "My Stories", "icon": "mdi mdi-book-multiple"}, {"id": "circletasks", "value": "My Tasks", "icon": "mdi mdi-calendar-multiple-check"}]}, "id": 37}, {"name": "tfgrid_solutions.ubuntu", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/ubuntu/", "status": 1, "source": {"name": "ubuntu", "threebot": "tfgrid_solutions", "description": "A free and open-source Linux distribution based on Debian.", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 38}, {"name": "tfgrid.wordpress", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/wordpress/", "status": 1, "source": {"name": "wordpress", "threebot": "tfgrid", "description": "A content managemet system (CMS)", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "tfgrid_solutions", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 39}, {"name": "threebot.appstore", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/appstore/", "status": 1, "source": {"name": "appstore", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 40}, {"name": "threebot.blog", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/core/", "status": 1, "source": {"name": "blog", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 41}, {"name": "threebot.calendar", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/calendar/", "status": 1, "source": {"name": "calendar", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 42}, {"name": "threebot.capacity", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/capacity/", "status": 1, "source": {"name": "capacity", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 43}, {"name": "threebot.contacts", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/contacts/", "status": 1, "source": {"name": "contacts", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 44}, {"name": "threebot.farmmanagement", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/farmmanagement/", "status": 1, "source": {"name": "farmmanagement", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 45}, {"name": "threebot.ffbrowser", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/ffbrowser/", "status": 1, "source": {"name": "ffbrowser", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 46}, {"name": "threebot.fileserver", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/fileserver/", "status": 1, "source": {"name": "fileserver", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 47}, {"name": "threebot.initialize", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/initialize/", "status": 1, "source": {"name": "initialize", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 48}, {"name": "threebot.mail", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threebot/mail/", "status": 1, "source": {"name": "mail", "threebot": "threebot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threebot", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 49}, {"name": "threefold.communityapp", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/communityapp/", "status": 1, "source": {"name": "communityapp", "threebot": "threefold", "description": "", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threefold", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 50}, {"name": "threefold.simplemail", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/simplemail/", "status": 1, "source": {"name": "simplemail", "threebot": "threefold", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threefold", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 51}, {"name": "threefold.simulator", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/simulator/", "status": 1, "source": {"name": "simulator", "threebot": "threefold", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threefold", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 52}, {"name": "threefold.tft_explorer", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/tft_explorer/", "status": 1, "source": {"name": "tft_explorer", "threebot": "threefold", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threefold", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 53}, {"name": "threefold.tf_websites", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/websites/", "status": 1, "source": {"name": "tf_websites", "threebot": "threefold", "description": "Umbrella package for threefold websites", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "", "namespace": "threefold", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 54}, {"name": "threefold.wikis", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/threefold/wikis/", "status": 1, "source": {"name": "wikis", "threebot": "threefold", "description": "threefold wikis for foundation, grid and tokens", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 55}, {"name": "zerobot.admin", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/admin/", "status": 3, "source": {"name": "admin", "threebot": "zerobot", "description": "admin dashboard", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "zerobot_admin", "namespace": "zerobot_admin", "type": 0, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 56}, {"name": "zerobot.alerta", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/alerta/", "status": 1, "source": {"name": "alerta", "threebot": "zerobot", "description": "alerting system for jumpscale", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [{"name": "system_alerta", "namespace": "", "type": 2, "instance": "default"}], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 57}, {"name": "zerobot.base", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/base/", "status": 3, "source": {"name": "base", "threebot": "zerobot", "description": "contains the system actors for each explorer", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 58}, {"name": "zerobot.chatbot_examples", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/chatbot_examples/", "status": 1, "source": {"name": "chatbot_examples", "threebot": "zerobot", "description": "examples for chatbot", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 59}, {"name": "zerobot.codeserver", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/codeserver/", "status": 1, "source": {"name": "codeserver", "threebot": "zerobot", "description": "A visual studio environment to host code", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 60}, {"name": "zerobot.myjobs_ui", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/myjobs/", "status": 3, "source": {"name": "myjobs_ui", "threebot": "zerobot", "description": "UI for myjobs", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 61}, {"name": "zerobot.oauth2", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/oauth2/", "status": 3, "source": {"name": "oauth2", "threebot": "zerobot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 62}, {"name": "zerobot.packagemanager", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/packagemanager/", "status": 3, "source": {"name": "packagemanager", "threebot": "zerobot", "description": "zerobot package manager", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 63}, {"name": "zerobot.github_webhooks", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/webhooks/", "status": 1, "source": {"name": "github_webhooks", "threebot": "zerobot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 64}, {"name": "zerobot.webinterface", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/webinterface/", "status": 3, "source": {"name": "webinterface", "threebot": "zerobot", "description": "zerobot API for gedis and bcdbfs", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 65}, {"name": "zerobot.webplatform", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/webplatform/", "status": 1, "source": {"name": "webplatform", "threebot": "zerobot", "description": "TBD", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 66}, {"name": "zerobot.wiki_examples", "giturl": "", "branch": "", "path": "/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/wiki_examples/", "status": 1, "source": {"name": "wiki_examples", "threebot": "zerobot", "description": "examples for wikis", "version": "1.0.0"}, "actor": {"namespace": ""}, "bcdbs": [], "description": "", "install_kwargs": {}, "frontend_args": {}, "id": 67}]}r
```

**Comment by john-kheir** [comment]
Verified

**Comment by robvanmieghem** [comment]
glad to see it also returns an http satus 400
