### ISSUE TITLE
new installation of the SDK ( 3bot2 container) "could not setup alerthandler"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#670]
Installed the 3bot SDK from scratch:

```
/tmp/sjx containers-delete
/tmp/jsx threebot
```

Installation successful but starting kosmos:
```
root@3bot:~# kosmos
could not setup alerthandler
Sat 28 14:24:31 ASECLASSES/JSBase.py - 379 - _logging_enable_check              : EXCEPTION: 
    AttributeError("'MyEnv_' object has no attribute 'log_includes'")
--TRACEBACK------------------
/sandbox/lib/jumpscale/jumpscale_generated.py in bcdb
    1357    self._bcdb =  BCDBFactory()
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in __init__
    59    self.__init_class()
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in __init_class
    142    self._logger_set(children=False, parents=False)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in _logger_set
    407    if not self._logging_enable_check():
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in _logging_enable_check
    379    if check(j.core.myenv.log_includes) and not check(j.core.myenv.log_excludes):
-----------------------------

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/__init__.py", line 28, in flush_bcdb
    for bcdb in j.data.bcdb.find():
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1357, in bcdb
    self._bcdb =  BCDBFactory()
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 66, in __init__
    self._init(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBFactory.py", line 23, in _init
    self._path = j.sal.fs.getDirName(os.path.abspath(__file__))
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 1737, in fs
    self._fs =  SystemFS()
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 59, in __init__
    self.__init_class()
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 142, in __init_class
    self._logger_set(children=False, parents=False)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 407, in _logger_set
    if not self._logging_enable_check():
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 379, in _logging_enable_check
    if check(j.core.myenv.log_includes) and not check(j.core.myenv.log_excludes):
AttributeError: 'MyEnv_' object has no attribute 'log_includes'
root@3bot:~# 
```

Did a pull from all the repo's:
```
oot@3bot:/sandbox/code/github/threefoldtech# for name in `ls`
> do
> cd $name
> echo $name
> git branch
> git pull
> cd ..
> done
home
* master
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
Already up to date.
jumpscaleX_builders
* development
Already up to date.
jumpscaleX_core
* development
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 62 (delta 35), reused 43 (delta 28), pack-reused 0
Unpacking objects: 100% (62/62), done.
From github.com:threefoldtech/jumpscaleX_core
   4f8f7a4f..f1f97c13  unstable              -> origin/unstable
   802ec5f0..796be412  unstable_jsxcontainer -> origin/unstable_jsxcontainer
Already up to date.
jumpscaleX_libs
* development
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 4), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (9/9), done.
From github.com:threefoldtech/jumpscaleX_libs
   6d460b5..f1b5a29  unstable   -> origin/unstable
Already up to date.
jumpscaleX_libs_extra
* development
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 19 (delta 5), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.
From github.com:threefoldtech/jumpscaleX_libs_extra
   63e156a..d89e7d6  unstable   -> origin/unstable
Already up to date.
jumpscaleX_threebot
* development
Already up to date.
jumpscaleX_weblibs
* master
Already up to date.
```
Did not solve it.

**Comment by weynandkuijpers** [comment]
Saw that there were updates to the unstable branch regardind logging.  Checked out unstable and development and both still do'nt start kosmos
```
root@3bot:~# kosmos
could not setup alerthandler
Sun 29 10:43:44 ASECLASSES/JSBase.py - 379 - _logging_enable_check              : EXCEPTION: 
    AttributeError("'MyEnv_' object has no attribute 'log_includes'")
```

**Comment by weynandkuijpers** [comment]
was something people we working on for another feature / bug.  for future documention and installation usage will create and use a seperate branch

Issues no longer relevant
