### ISSUE TITLE
SAL.FS: Compressing directory using targzCompress fails if this directory contains a symlink for a directory.

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#68]
### Steps:
1- Create a directory `test_dir`.
2- Create a sub directory `subdir` under `test_dir`.
3- Create a symlink for `subdir` inside `test_dir`.
4- Compress `test_dir`.
```
j.sal.fs.targzCompress("/tmp/test_dir", "/tmp/test.tar", followlinks=True) 
```

### Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 1705, in targzCompress
    followlinks=False,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSWalker.py", line 151, in walk
    followlinks=followlinks,
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSWalker.py", line 220, in _walk
    callback(arg, path2)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 1689, in addToTar
    raise j.exceptions.RuntimeError("Cannot add file %s to destpath" % destpath)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.RuntimeError1: ?[1;31mEXCEPTION: 
    Cannot add file sym to destpath?[0;0m

?[1;31mEXCEPTION: 
    Cannot add file sym to destpath?[0;0m
```

**Comment by ranatrk** [comment]
Fixed with the following issue fixed: https://github.com/threefoldtech/jumpscaleX_core/issues/69

**Comment by ranatrk** [comment]
According to https://docs.python.org/3/library/tarfile.html `TarFile.add(...) ` adds any type of file (directory, fifo, symbolic link, etc.)
This fixes the issue that links are not added as well as the mentioned bug where an error is raised due to the Dir being checcked not just files and links.
Fix : https://github.com/threefoldtech/jumpscaleX_core/commit/a28e589873e8c65ff44a5b65721b0e04c1fbe50d

**Comment by hossnys** [comment]
verified on development a28e589
```
JSX> j.sal.fs.targzCompress("/test_dir/", "/tmp/test.tar", followlinks=True)  
JSX> j.sal.fs.targzUncompress("/tmp/test.tar", "/tmp/testing")
```
```
3BOTDEVEL:test:testing: ls -alh
total 16K
drwxr-xr-x  4 root root 4.0K Sep 10 15:49 .
drwxrwxrwt 13 root root 4.0K Sep 10 15:50 ..
drwxr-xr-x  2 root root 4.0K Sep 10 15:49 sub_dir
drwxr-xr-x  2 root root 4.0K Sep 10 15:41 sub_dir2

3BOTDEVEL:test:sub_dir2: ls
file
```
