### ISSUE TITLE
SAL.FS: Removing all symlinks under diectory fails if this directory contains a symlink for a directory.

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#69]
### Steps:
1- Create a directory `test_dir`.
2- Create a file `test_file` inside `test_dir`
3- Create a sub directory `subdir` under `test_dir`.
4- Create links for `test_dir` and the destination `sym_test`
```
j.sal.fs.symlinkFilesInDir("/tmp/test_dir", "/tmp/sym_test", includeDirs=True)
```
5- Remove all symlinks in the destination directory.
```
j.sal.fs.removeLinks("/tmp/sym_test")
```
### Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 674, in removeLinks
    self.unlink(item)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 182, in wrapper
    % (parameter.name, jslocation(), func.__name__, value)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.Value1: ?[1;31mEXCEPTION: 
    Argument filename in j.sal.fs.unlink expects a file path! /tmp/sym_test/subdir is not a file.?[0;0m

?[1;31mEXCEPTION: 
    Argument filename in j.sal.fs.unlink expects a file path! /tmp/sym_test/subdir is not a file.?[0;0m
```

**Comment by ranatrk** [comment]
Fix : https://github.com/threefoldtech/jumpscaleX_core/commit/5188c5ffc78e27d07ce2d4f6ffdbf1ce8c6f7c2f

**Comment by hossnys** [comment]
verified on development 5188c5f 
```
JSX> j.sal.fs.symlinkFilesInDir("/tmp/test_dir", "/tmp/sym_test", includeDirs=True)              
JSX> j.sal.fs.removeLinks("/tmp/sym_test")                                                                                                                                                                      
```
