### ISSUE TITLE
Error starting a halted 3bot container using 3sdk

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#753]
branch development commit c99a93e849f64e65ac91f393a5e3473d60386977
```
3sdk> container start

@param server=True will start 3bot server

3bot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/sandbox/code/github/threefoldtech/jumpscaleX_core/install/threesdk/container.py", line 120, in start
    c = _containers.get(name=name)
  File "/Users/rob/sandbox/code/github/threefoldtech/jumpscaleX_core/install/threesdk/lib/SDKContainers.py", line 74, in get
    if not docker.executor.exists("/sandbox/cfg/.configured"):
  File "/Users/rob/sandbox/code/github/threefoldtech/jumpscaleX_core/install/threesdk/InstallTools.py", line 5402, in executor
    if not self._executor:
AttributeError: 'DockerContainer' object has no attribute '_executor'

'DockerContainer' object has no attribute '_executor'
3sdk> container list

list the containers

 - 3bot       : localhost       : threefoldtech/3bot2       (sshport:9000)
3sdk> container kosmos

start kosmos shell

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rob/sandbox/code/github/threefoldtech/jumpscaleX_core/install/threesdk/container.py", line 104, in kosmos
    c = _containers.get(name=name)
  File "/Users/rob/sandbox/code/github/threefoldtech/jumpscaleX_core/install/threesdk/lib/SDKContainers.py", line 74, in get
    if not docker.executor.exists("/sandbox/cfg/.configured"):
  File "/Users/rob/sandbox/code/github/threefoldtech/jumpscaleX_core/install/threesdk/InstallTools.py", line 5402, in executor
    if not self._executor:
AttributeError: 'DockerContainer' object has no attribute '_executor'

'DockerContainer' object has no attribute '_executor'
```

**Comment by robvanmieghem** [comment]
It worked today
