### ISSUE TITLE
Redis client is broken

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#9]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py", line 702, in __call__
    printer.pretty(obj)
  File "/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py", line 402, in pretty
    return _repr_pprint(obj, self, cycle)
  File "/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py", line 697, in _repr_pprint
    output = repr(obj)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 783, in __str__
    out = add("children", "GREEN", self._children_names_get(), out)
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 618, in _children_names_get
    return self._filter(filter=filter, llist=self._children_get(filter=filter))
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 235, in _children_get
    for item in self.find():
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 149, in find
    for jsxobject in self._findData(**kwargs):
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py", line 190, in _findData
    return self._model.find()
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py", line 68, in __getattr__
    raise j.exceptions.NotFound(msg)
Jumpscale.core.InstallTools.JSExceptions.__init__.<locals>.NotFound1: {RED}EXCEPTION: 
    could not find attribute:_model in redisfactory (error was:type object 'RedisFactory' has no attribute '_CHILDCLASS'){RESET}
```

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/a1703871b3faf7d1c8060607dcf0dcd7c324ba0f
